name: 🐛 Bug Report
description: Report a reproducible bug or regression.
type: bug
labels: ['Status: Unconfirmed']
title: 'Bug: '
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! Please fill this template out as completely as possible.
        * If you are not reporting a bug, but want to ask a general question, use [discussions](https://github.com/muxinc/elements/discussions) instead.
        * Check the [docs](https://docs.mux.com/guides/player?utm_source=github-mux-player).
        * Please check to see if there's an existing issue and replying there instead.
        * Please give as much details as you can. Ideally, include a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: dropdown
    id: elements
    attributes:
      label: Which Mux Elements/Packages does this apply to? Select all that apply
      multiple: true
      options:
        - mux-video
        - mux-video-react
        - mux-audio
        - mux-audio-react
        - mux-player
        - mux-player-react
        - mux-uploader
        - mux-uploader-react
        - playback-core
        - common
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Which browsers are you using?
      description: Currently, Mux Elements are only officially supported in new version of the browsers listed.
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Edge ("Edgeium")
        - Chrome Android
        - Safari on iOS
        - Other (add details below)
    validations:
      required: true
  - type: dropdown
    id: oses
    attributes:
      label: Which operating systems are you using?
      options:
        - Windows
        - macOS
        - iOS
        - Android
        - Other (add details below)
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide a clear and concise description of what the bug is. Include
        screenshots if needed. Please test using the latest version of the relevant
        Mux Elements packages to make sure your issue has not already been fixed.
    validations:
      required: true
  - type: input
    id: testcase
    attributes:
      label: Reduced test case
      description: |
        Please add a URL to a [reduced test case](https://stackoverflow.com/help/minimal-reproducible-example).
        This can be a codesandbox or a GitHub repo.
        Providing makes it easier to reproduce the issue and getting it fixed.
      placeholder: https://
  - type: textarea
    id: str
    attributes:
      label: Steps to reproduce
      description: |
        Detailed steps to reproduce the issue.
        Your bug will get fixed much faster if we can run your code and it's clear how to reproduce the issue.
        Issues without reproduction steps or code examples may be immediately closed as not actionable.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: actualbehavior
    attributes:
      label: Current Behavior
    validations:
      required: true
  - type: textarea
    id: expectedbehavior
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: errors
    attributes:
      label: Errors
      description: If you see any errors in the console, please include them there
  - type: input
    id: version
    attributes:
      label: What version of the package are you using?
      description: Please include the version you are using. If you are not using the latest version, please explain why in the description above.
      placeholder: vX.Y.Z
