// @ts-nocheck
import { createTemplateInstance } from '../html';
import airplayIcon from './icons/airplay.svg';
import captionsOffIcon from './icons/captions-off.svg';
import captionsOnIcon from './icons/captions-on.svg';
import castEnter from './icons/cast-enter.svg';
import castExit from './icons/cast-exit.svg';
import fullscreenEnter from './icons/fullscreen-enter.svg';
import fullscreenExit from './icons/fullscreen-exit.svg';
import pause from './icons/pause.svg';
import pipEnter from './icons/pip-enter.svg';
import pipExit from './icons/pip-exit.svg';
import play from './icons/play.svg';
import seekBackward from './icons/seek-backward.svg';
import seekForward from './icons/seek-forward.svg';
import volumeHigh from './icons/volume-high.svg';
import volumeLow from './icons/volume-low.svg';
import volumeMedium from './icons/volume-medium.svg';
import volumeOff from './icons/volume-off.svg';

export const Airplay = () => createTemplateInstance(airplayIcon);
export const CaptionsOff = () => createTemplateInstance(captionsOffIcon);
export const CaptionsOn = () => createTemplateInstance(captionsOnIcon);
export const CastEnter = () => createTemplateInstance(castEnter);
export const CastExit = () => createTemplateInstance(castExit);
export const FullscreenEnter = () => createTemplateInstance(fullscreenEnter);
export const FullscreenExit = () => createTemplateInstance(fullscreenExit);
export const Pause = () => createTemplateInstance(pause);
export const PipEnter = () => createTemplateInstance(pipEnter);
export const PipExit = () => createTemplateInstance(pipExit);
export const Play = () => createTemplateInstance(play);
export const SeekBackward = (p: any) => createTemplateInstance(seekBackward, p);
export const SeekForward = (p: any) => createTemplateInstance(seekForward, p);
export const VolumeHigh = () => createTemplateInstance(volumeHigh);
export const VolumeLow = () => createTemplateInstance(volumeLow);
export const VolumeMedium = () => createTemplateInstance(volumeMedium);
export const VolumeOff = () => createTemplateInstance(volumeOff);
