name: Deployment of News player components

on:
  push:
    branches:
      - main-news-player

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: read node version from the .nvmrc file
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        shell: bash
        id: nvmrc
      - uses: actions/setup-node@v4
        with:
          node-version: ${{steps.nvmrc.outputs.NODE_VERSION}}
          # this line is required for the setup-node action to be able to run the npm publish below.
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci
      - name: Clean
        run: npm run clean
      # - name: Test
      #   run: npm test
      - name: Clean
        run: npm run clean
      - name: Build
        run: npm run build:packages

      - uses: fregante/setup-git-user@v2
      - name: Append !dist to gitignore
        run: echo '!dist' >> .gitignore
      - name: Stage dist folders
        run: git add --all
      - name: Commit changes to git
        run: git commit -m "Add dist folders"
      - name: Force push to release-news-player
        run: git push -uf origin release-news-player
