name: Deployment of News player components

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches
      - name: read node version from the .nvmrc file
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
        shell: bash
        id: nvmrc
      - uses: actions/setup-node@v4
        with:
          node-version: ${{steps.nvmrc.outputs.NODE_VERSION}}
          # this line is required for the setup-node action to be able to run the npm publish below.
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci
      - name: Clean
        run: npm run clean
      # - name: Test
      #   run: npm test
      - name: Clean
        run: npm run clean
      - name: Build
        run: npm run build:packages

      # Require the custom version of mux-player and mux-video-ads
      # Do it here so we still automatically workspace symlink during development.
      - name: Update NPM @mux/mux-player version to gitpkg url
        run: npm pkg set dependencies.@mux/mux-player='https://gitpkg.vercel.app/muxinc/elements/packages/mux-player?release-news-player' -w @mux/mux-player-react
      - name: Update NPM @mux/mux-video-ads version to gitpkg url
        run: npm pkg set dependencies.@mux/mux-video-ads='https://gitpkg.vercel.app/muxinc/elements/packages/mux-video-ads?release-news-player' -w @mux/mux-player-react

      - uses: fregante/setup-git-user@v2
      - name: Append !dist to gitignore
        run: echo '!dist' >> .gitignore
      - name: Stage dist folders
        run: git add --all
      - name: Commit changes to git
        run: git commit -m "Add dist folders"
      - name: Force push to release-news-player
        run: git push -f origin main-news-player:release-news-player
