name: Add new issues and PRs to the Project

on:
  issues:
    types:
      - opened
      - transferred
  pull_request:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issues and PRs to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/muxinc/projects/8/views/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
